var COMMANDS  = { "en" : {
  "voice" : "UK English Female",
  "default" : 'Say "What can I say?" to see a list of commands...',
  "hi" : 'Hi, sexy!',
  "whatcanisay" : 'What can I say',
  "home" : 'Go home',
  "sleep" : 'Go to sleep',
  "wake" : 'Wake up',
  "debug" : 'Show debug information',
  "map" : 'Show map',
  "locaiton" : 'Show (me a) map of *location',
  "zoomin" : '(map) zoom in',
  "zoomout" : '(map) zoom out',
  "zoomvalue" : '(map) zoom (to) *value',
  "zoomreset" : '(map) reset zoom',
  "term" : 'Show me *term',
  "name" : 'My (name is)(name\'s) *name',
  "task" : 'Remind me to *task',
  "reminder" : 'Clear reminders',
  "clear" : 'Clear results',
  "time" : 'what time is it',
  "light" : '(turn) (the) :state (the) light(s) *action',
  "playyoutube" : 'play *term youtube',
  "ytbplaylist" : '*term playlist',
  "stopyoutube" : 'stop youtube',
  "subway" : 'show me *linenumber info at *station',
  "musicplay" : "play music *track",
  "musicreplay" : "replay music",
  "musicresume" : "resume music",
  "musicstop" : "stop music",
  "info" :  "Here is a list of commands..."
},
  "ko" : {
    "voice" : "Korean Female",
    "default" : '"사용 가능한 질문" 이라 말해 보세요',
    "hi" : '안녕 embian',
    "whatcanisay" : '사용 가능한 질문',
    "home" : '(집)(메인 화면)',
    "sleep" : '잠자러가',
    "wake" : '일어나',
    "debug" : '디버그 정보 보여 줘',
    "map" : '지도 보여 줘',
    "locaiton" : '*location지도 보여 줘',
    "zoomin" : '지도 확대',
    "zoomout" : '지도 축소',
    "zoomvalue" : '*value값으로지도 설정',
    "zoomreset" : '지도 리셋',
    "term" : '*term 보여 줘',
    "name" : '나(는)(의 이름은) *name이야',
    "task" : '*task 상기 시켜 줘',
    "reminder" : '리마인더 제거해 줘',
    "clear" : '결과 없애 줘',
    "time" : '지금 몇 시',
    "light" : '불 :state *action (해)줘',
    "playyoutube" : '*term 동영상 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "ytbplaylist" : '*term 플레이어 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "stopyoutube" : '동영상 (꺼 봐)(꺼 줘)(정지)(중지)(그만)(꺼져)',
    "subway" : '*station역 *linenumber(호)선 *updown',
    "musicplay" : "*track 음악 (재생)(켜 줘)",
    "musicreplay" : "음악 다시 시작",
    "musicresume" : "음악 다시 재생",
    "musicstop" : "음악 (꺼 봐)(꺼 줘)(정지)(중지)(꺼져)",
    "info" : "다음은 사용 가능한 질문입니다."
  }
};
